### ISSUE TITLE
KeyError: 'Resources' 

### ISSUE THREAD

**Issue by boneyt** [ModusVivendi/twitter-contest#15]
Getting the following error message when running the script,

Traceback (most recent call last):
  File "main.py", line 435, in <module>
    CheckRateLimit()
  File "main.py", line 182, in CheckRateLimit
    for res_family in r['resources']:
KeyError: 'resources'

**Comment by AuxProc** [comment]
It looks like you're requesting the Rate Limit from the twitter API, but the API is not returning what CheckRateLimit expects.  Could this be an authentication issue?

**Comment by Asundawn** [comment]
got the same error also

**Comment by Asundawn** [comment]
its working now. i have a question for how much time should i run it continuously.

**Comment by Asundawn** [comment]
And i think you should also add "#Giveaway" and "entered to win" in search queries also. And could i do this manually in main.py

**Comment by AuxProc** [comment]
search queries are a configuration option in config.json.  Just add whatever queries you would like to that file.

**Comment by AuxProc** [comment]
The script schedules the number of retweets per day listed in the daily-retweets option in config.json. Rather than running and stopping the script manually, just enter a number you find appropriate in the daily-retweets parameter.  The example file default is 300 retweets per day, which is a good place to start.
